 version: '3'
 services:
  flask:
   image: webapp-flask
   build:
    context: .
    dockerfile: Dockerfile-flask
   volumes:
    - "./:/app"
  nginx:
   image: webapp-nginx
   build:
    context: .
    dockerfile: Dockerfile-nginx
   ports:
    - 5000:80
   depends_on:
    - flask

  mongodb:
    image: mongo:latest
    container_name: uv-mongodb
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --auth
    